name: HTML Accessibility Test
on:
  workflow_dispatch:

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@main
   with:
     target_url: https://spacetelescope.github.io/${{ github.event.repository.name }}/
   secrets:
     A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN2 }}
