name: Weekly HTML Accessibility Check
on:
  schedule:
    - cron: '0 4 * * 0' # 0400 UTC every Sunday
  workflow_dispatch:

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@v3
   with:
     target_url: https://spacetelescope.github.io/${{ github.event.repository.name }}/
     python-version: ${{ vars.PYTHON_VERSION }}
   secrets:
     A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
